### ISSUE TITLE
Postman Proxy Server

### ISSUE THREAD

**Issue by CrescentSapphire** [blessedlex/Skynet-Zuckerberg-Edition#16]
Working on a fix for proxy server connection to capture.

**Comment by CrescentSapphire** [comment]
Setting up proxy server. Working on connectivity next.

**Comment by blessedlex** [comment]
What do you need to get the connectivity working @CrescentSapphire ?

**Comment by CrescentSapphire** [comment]
Fixed connectivity, with switching tools in Postman. We are now using Interceptor which is similar to a proxy but is made for capturing the same device capture information. Much easy for capturing data.
