### ISSUE TITLE
packet capturing challenges

### ISSUE THREAD

**Issue by blessedlex** [blessedlex/Skynet-Zuckerberg-Edition#17]
information from the media uploads was encrypted then had to be decrypted using Wireshark. Sasha captured the packet we are currently combing through. Going to post any significant data we find here

**Comment by sashaprice** [comment]
potential keylogger being used -- CalvaryLogger (javascript code contains references in packet capture)

**Comment by sashaprice** [comment]
It appears Facebook is using Babel to compile their JS code

**Comment by blessedlex** [comment]
No challenges presented any longer with this issue. Closing ticket.
