### ISSUE TITLE
create Facebook test account to test tagging and determine accuracy behavior and bias

### ISSUE THREAD

**Issue by blessedlex** [blessedlex/Skynet-Zuckerberg-Edition#18]
post screenshots here of the UI and testing -- go through the settings of how a user can turn on or turn off the facial recognition feature and record by taking detailed notes &/or screenshots

**Comment by blessedlex** [comment]
Facebook Account: dshiparo97@gmail.com

**Comment by blessedlex** [comment]
First thing that is seen once you create a new account and go to facial recognition settings.

![1st Capture](https://user-images.githubusercontent.com/28307295/97242380-b784e900-17c1-11eb-917e-a4f63826b5d5.PNG)
![2 Capture](https://user-images.githubusercontent.com/28307295/97242384-b8b61600-17c1-11eb-8a22-c215503d1b02.PNG)

**Comment by smmay97** [comment]
![Uploading image.png…]()

**Comment by blessedlex** [comment]
Next, with facial recognition turned off, the user cannot be auto-tagged in any uploads from another user on Facebook.

![3 Capture](https://user-images.githubusercontent.com/28307295/97248951-df2f7d80-17d0-11eb-956a-a331d1b30f3a.PNG)
![5 Capture](https://user-images.githubusercontent.com/28307295/97248957-e48cc800-17d0-11eb-82ed-e5117d7658c0.PNG)

**Comment by smmay97** [comment]
Sean's personal account facial recognition setting set to ON.

![Sean Account Screen Shot](https://user-images.githubusercontent.com/47121433/97249063-1c940b00-17d1-11eb-865b-41c37c01f255.PNG)

**Comment by blessedlex** [comment]
Sean has his setting on, he was auto-tagged in Devin's upload before the post was even submitted.

![6 Capture](https://user-images.githubusercontent.com/28307295/97249138-40efe780-17d1-11eb-9eed-930dab039707.PNG)
![7 Capture](https://user-images.githubusercontent.com/28307295/97249143-42211480-17d1-11eb-9ab9-27b3a703701e.PNG)

**Comment by blessedlex** [comment]
With my setting off (on my personal account), I was not auto-tagged through the test account upload.

![15 Capture](https://user-images.githubusercontent.com/28307295/97339426-928b8700-1850-11eb-8313-974cc4f0357f.PNG)
![11 Capture](https://user-images.githubusercontent.com/28307295/97249189-59f89880-17d1-11eb-8623-1761291abb35.PNG)
![12 Capture](https://user-images.githubusercontent.com/28307295/97249191-5b29c580-17d1-11eb-8661-f0baaedf018c.PNG)
![13 Capture](https://user-images.githubusercontent.com/28307295/97249194-5c5af280-17d1-11eb-895a-c5a630ba6df8.PNG)

**Comment by blessedlex** [comment]
After asking a friend for permission to use their photo for the test (Devin Shiparo) account, I tried tagging him from my personal profile AFTER setting Devin's facial recognition setting to ON. The auto-tag feature did not initiate to tag my friend's face.

Note: This may be due to Facebook needing more facial data of my friend before determining that he is Devin from another user's account.

![14 Capture](https://user-images.githubusercontent.com/28307295/97250681-7944f500-17d4-11eb-9479-4ae1fd24e034.PNG)

**Comment by MLHale** [comment]
ok, so the interface is doing what it is supposed to do. What does this tell us? How do you know if they are still doing facial recognition anyway? 

If the research question is in regards to whether facebook is complying with their stated policies and respecting user privacy - how do you know? Just because the interface doesnt show tagged data, doesn't mean it doesnt exist.

**Comment by blessedlex** [comment]
We are shifting our focus into using this testing to obtain any bias and implications for privacy. We are still testing through the UI to get the accuracy of this auto-tagging/manual tagging behavior to potentially be able to replicate it and determine bias.

There have been some inaccuracies noted in this testing. Although the interface may not show the tagged data for user's to see on the UI, the behavior of the tagging and its accuracy are what we want to test to pull any implicit bias, population bias, and privacy implications on.

From the use of my friend's photo, he was not tagged as himself nor was he tagged for Devin. Why is that? The data exists because it has been uploaded but the UI is not accurately tagging/auto-tagging the person. What does an observation of this behavior potentially mean?
