### ISSUE TITLE
Using Postman's API

### ISSUE THREAD

**Issue by blessedlex** [blessedlex/Skynet-Zuckerberg-Edition#9]
investigating this API

**Comment by sashaprice** [comment]
[Here is a good link](https://learning.postman.com/docs/sending-requests/capturing-request-data/capturing-http-requests/) for specifically capturing requests in Postman

**Comment by sashaprice** [comment]
It looks like [Postman's Interceptor extension](https://chrome.google.com/webstore/detail/postman-interceptor/aicmkgpgakddgnaphhhpliifpcfhicfo?hl=en) for Chrome is probably the best way to handle capturing traffic.

**Comment by MLHale** [comment]
Lab from 8470 grad class https://mlhale.github.io/CYBR8470/modules/penetration-testing/

**Comment by blessedlex** [comment]
@CrescentSapphire maybe this information would useful for fixing the proxy issue? Not sure if you've seen this yet

**Comment by blessedlex** [comment]
This info for Dr. Hale's library is useful for HTTP: [https://github.com/MLHale/CYBR8470/tree/master/modules/restful-api](https://github.com/MLHale/CYBR8470/tree/master/modules/restful-api)

**Comment by blessedlex** [comment]
Postman provided the HTTP method capture we included in our Milestone 2
